### ISSUE TITLE
Base中监听toast只适合单Activity项目吧，toast多次显示

### ISSUE THREAD

**Issue by StefanTimber** [ldlywt/FastJetpack#14]
感谢大佬分享！
如果有多个Act，发送Toast每个都会收到，导致重复显示，除了用LiveEventBus还有没有其他好的解耦方案？

**Comment by ldlywt** [comment]
网络库中的这个toast只是一个Demo方案，不要这么使用。。。
项目上okhttp拦截器就会有很多个，我一般情况下会在Application初始化的

**Comment by StefanTimber** [comment]
明白了，谢谢
