### ISSUE TITLE
作者你好，没有明白launchAndCollectIn封装的使用场景

### ISSUE THREAD

**Issue by ljphawk** [ldlywt/FastJetpack#17]
launchAndCollectIn里边封装使用到了repeatOnLifecycle方法，但目前你demo的使用场景中，每次我让此Fragment生命周期onStart一下，collect函数便会回调一下上次新数据，感觉毫无意义。

**Comment by ldlywt** [comment]
Flow 不具备 LiveData 的生命周期感知能力，所以订阅者在监听 Flow 数据流时，会存在生命周期安全的问题
