### ISSUE TITLE
关于oneWay封装一，因为我现在就在用这中，想跟你了解下不推荐的原因

### ISSUE THREAD

**Issue by dovefairy** [ldlywt/FastJetpack#21]
oneWay封装一耦合高是指复用性差吗？还有传递UI引用是指ViewModel的生命周期绑定吗？

**Comment by ldlywt** [comment]
https://juejin.cn/post/6993294489125126151#heading-2

具体可以看下这篇。
其实每一种方式都可以，适合自己项目的才是最好的。
