### ISSUE TITLE
调度问题

### ISSUE THREAD

**Issue by ghost** [ldlywt/FastJetpack#6]
你没有调度到io，hongyang不回复我

**Comment by ldlywt** [comment]
我没懂你的意思，你指的是网络请求没有在IO线程么？retrofit内部已经处理了线程切换

**Comment by ldlywt** [comment]
你这种人真的是有意思，你自己对协程底层怎么切换线程的知识不懂，跑过来质问我，我发了几篇讲这个的文章给你看，你自己不看，一直只知道问我，现在上班时间点，并且我俩又不认识，我有什么义务来告诉你，你是不是觉得你问别人问题，别人就一定要有义务告诉你，不告诉你别人就有错？

你自己看看聊天记录，全是质问的语气？我就是知道也不告诉你，因为我觉得我花这个时间跟你讨论，是浪费我的时间，并且对我也没什么好处。

并且我写文章也没必要去请你看吧，你看不看，用不用我的代码对我有什么好处么？我收费了还是怎么着？、

还有，我哪里摆什么庄家谱了？

我从没见过加人微信，上来招呼都不打，直接就是一张图，然后说我手受伤了，不方便打字。

素质真低。

**Comment by ldlywt** [comment]
并且我们微信聊天，我没有说任何脏话吧，我实在不想跟你聊下去，把你微信拉黑了，微信是我个人生活微信，不想加陌生人，你跑到github来骂我，这种行为也确实厉害。

**Comment by ldlywt** [comment]
笑死了，我赚流量，我赚流量干嘛，我又不开课程，不做公众号，不做自媒体。

"hongyang公众号有你的推文，有没有吃烂钱，大家心知肚明"  ????

这句话很有意思，请问：
1.我为什么要花钱让人推我的文章，对我有什么好处？？？

2. hongyang 搞了这么多年Android，很多看着的博客学习成长，他的人品怎么样，你不知道？

3.我的项目有问题，hongyang难道不知道？很多看过的难道不知道？

4.就算我项目有问题，你指出来，我改不改是我自己的问题吧，但是你也没必要上升到人身攻击吧

**Comment by ldlywt** [comment]
![image](https://user-images.githubusercontent.com/17981095/138417134-f21df4c1-54f3-4a9c-abdf-2f261ee6a288.png)

刚才看了下评论，你的问题hongyang回答你了，自己去看吧

**Comment by ldlywt** [comment]
第一：我不认识hongyang，我也问不到他，我也没他微信
第二：我不懂的东西我会先去谷歌搜，看博客，看stackoverflow。而不是气势冲冲去质问一个陌生人。
第三：别人不想跟你讨论，不是代表别人不懂，只是不想花费无用的时间。
第四：身为成年人，看了别人的开源项目，可以选择用或者不用，别人提供的只是一种思想，而不是一种代码copy。
第五：你烦着，跟其他人没任何关系，别人没责任义务来跟你一起烦着。
第六：上一条评论道歉，下一条又是气势冲冲。
第七：技术交流不要涉及到人身攻击，如果说话不会礼貌，请去看叫人学礼仪的书籍。
第八：打电话给你陌生人，第一句话是：你好。自我介绍。

**Comment by ldlywt** [comment]
再跟你说一句，我跟hongyang之间技术距离，我自己知道，中间至少隔了10个你

**Comment by ldlywt** [comment]
果然素质差跟菜是有联系的

**Comment by ldlywt** [comment]
从我做Android开始，我就很喜欢hongyang和guolin，他们两也是我的领路人。我的文章被他微信号推了，我很开心，因为我的文章被我喜欢的大神得到了认可。他赚不赚钱我不在意，也不介意。
别人不回答你的问题，并不是别人不懂，只是不想花这个时间来讨论。
我这个项目框架我在我公司的项目中已经稳定运行了几个月，几十上百个接口没有出行问题。
有没有问题，自己用一下就知道了，自己用都不用就过来指责别人的有问题，low的行为。

**Comment by AoEiuV020** [comment]
v站过来围观，
没看代码，但网络请求没切换线程是会直接崩溃的吧，怎么想也不会有这么大坑，

**Comment by bob-zebedy** [comment]
v2来围观，不管技术，我先替作者report了这个 @Temtion 
<img width="863" alt="Google Chrome-GitHub Support-20211022182411" src="https://user-images.githubusercontent.com/53208952/138438537-b3c3599b-9af3-4130-8779-6f4e45fa36b6.png">

**Comment by hongyangAndroid** [comment]
不好意思，还是同事给我发的链接才发现这个事情。

@ldlywt 

非常抱歉给作者带来困扰；

@Temtion 

没回复这个事情是这样的，其实大家每天提问，其中很多问题我也是不懂的，我就放出来随缘看看大家建议，如果你觉得被冒犯，我可以致歉，但是确实没法改变；

>另外还有一些消息还有可能不会被放出来，因为过了一个时间点，我就不会回去看留言了。

此外，从上面对话来看人身攻击太过分了，开源更多的是共建而不是索取。

最后，就从这个开源库所涉及到的知识来说，作者比我懂得多。

**Comment by ghost** [comment]
感谢弘扬大佬百忙之中回复，开源是共建，说的很对！
当初也用过您很多库，理当怀有感恩之心。
做技术的不可能清楚每一个细节。
您是不清楚整个事件，原作者每一句敷衍和不着边际都在损害着你的形象，因为如果不是你，这个事情压根不会有。
错误不是我纠结的点，态度是。
也请领袖爱惜自己的羽毛，不要发一些自己不是特别透彻的，因为你是领袖，你的错误，只会被放大。
然而，事情持续到现在，没有一个特较真的告诉我，哪里切到了io？


发自我的iPhone

**Comment by ldlywt** [comment]
> 不好意思，还是同事给我发的链接才发现这个事情。
> 
> @ldlywt
> 
> 非常抱歉给作者带来困扰；
> 
> @Temtion
> 
> 没回复这个事情是这样的，其实大家每天提问，其中很多问题我也是不懂的，我就放出来随缘看看大家建议，如果你觉得被冒犯，我可以致歉，但是确实没法改变；
> 
> > 另外还有一些消息还有可能不会被放出来，因为过了一个时间点，我就不会回去看留言了。
> 
> 此外，从上面对话来看人身攻击太过分了，开源更多的是共建而不是索取。
> 
> 最后，就从这个开源库所涉及到的知识来说，作者比我懂得多。

鸿阳大神，你没必要跟他致歉之类的，不知道，你怀着好心分享技术文章，他觉得你每一篇文章都跟作者有PY交易

**Comment by AoEiuV020** [comment]
@Temtion 人一开始就说了是retrofit内部处理的线程切换，
以前的retrofit需要service里指定返回Call就能切换线程异步处理，
现在的retrofit只要写了suspend使用协程就就会被retrofit异步处理不需要另外处理线程切换，
具体retrofit怎么判断协程处理的你应该去retrofit问，

**Comment by ygl-rg** [comment]
這種人不b留著過年？

**Comment by ldlywt** [comment]
关于协程是怎么进行线程切换的，这两篇文章写的很好了，我在微信里也发给他了，但是他不看啊，一直只质问我。

https://juejin.cn/post/6883652600462327821?share_token=516bd111-33f9-4450-86e7-0a91cd816afd

https://juejin.cn/post/6981056016897015838?share_token=01a2eba4-365d-40f8-ac26-b31ffe0f72d2

**Comment by ghost** [comment]
> 关于协程是怎么进行线程切换的，这两篇文章写的很好了，我在微信里也发给他了，但是他不看啊，一直只质问我。
> 
> https://juejin.cn/post/6883652600462327821?share_token=516bd111-33f9-4450-86e7-0a91cd816afd
> 
> https://juejin.cn/post/6981056016897015838?share_token=01a2eba4-365d-40f8-ac26-b31ffe0f72d2

1.suspend 没有切换线程 这个不用多说吧
2.协程中的调度器，Dispatchers.IO 才能指定协程实际运行环境
3.retrofit中看到协程有那里 指定调度器吗？
4.指定调度器两种方式：WithContext(Dispatchers.xx) 或者 launch(Dispatchers),或许还有其他指定的方式，这就是我自己认知的不足了，retrofit中没有找到相关的代码

**Comment by AoEiuV020** [comment]
@Temtion 还没明白吗，问题在于1. 你想知道的别人未必想知道，2. 别人知道的未必要告诉你，这个issue到2楼就可以结束了，之后就该你自己去研究retrofit了，

就当我咸的，我给你看看吧，

结论是，协程确实是运行在主线程，没有用调度器什么的也不需要，retrofit默认是使用okhttp的io线程池异步请求的网络，

看你上面已经找到.await()->enque()，那这之前就不说了，然后就是，
retrofit/src/main/java/retrofit2/Call.java:49
默认实现在，
retrofit/src/main/java/retrofit2/OkHttpCall.java:147
```java
    okhttp3.Call call;
    call.enqueue(...);
```
然后就到了okhttp项目里了，
https://github.com/square/okhttp
okhttp/src/main/java/okhttp3/Call.java:71
默认实现在，
okhttp/src/main/java/okhttp3/RealCall.java:93
```java
    client.dispatcher().enqueue(new AsyncCall(responseCallback));
```
okhttp/src/main/java/okhttp3/Dispatcher.java:135
```java
      readyAsyncCalls.add(call);
```
把call加入列表中然后当前线程就返回了，

到这里已经知道这里retrofit没有在主线程进行网络连接了，

然后readyAsyncCalls是在promoteAndExecute方法中取出来运行的，
okhttp/src/main/java/okhttp3/Dispatcher.java:204
```java
      AsyncCall asyncCall = executableCalls.get(i);
      asyncCall.executeOn(executorService());
```
这里的executorService就是okhttp内部用的io线程池了，
okhttp/src/main/java/okhttp3/Dispatcher.java:65
```java
      executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE, 60, TimeUnit.SECONDS,
          new SynchronousQueue<>(), Util.threadFactory("OkHttp Dispatcher", false));
```
而executeOn就是简单调用execute异步处理的，
okhttp/src/main/java/okhttp3/RealCall.java:154
```java
        executorService.execute(this);
```
execute再进去就是java内部了，

**Comment by ghost** [comment]
> ```java
>  client.dispatcher().enqueue(new AsyncCall(responseCallback));
> ```
显然，你也认为retrofit没有做线程切换这方面的操作。
 那会有这么个问题，Rxjava也有调度器机制即 Scheduler, 
 当初rx+retrofit+ok时候，为何要指定调度两次，即切走请求再切回来响应？
 如今只是协程 替换掉了rx，会不会奇怪?
 ————————————————————————————————————————————
 是不是retrofit 对 非挂起处理是call.execute(),
挂起处理是 call.enqueue() ？
@ldlywt 上面这两行是key,  今天是烦劳您了，不过得到答案也有点辛苦，因为思维定势了，忘记了enqueue和excecute区别了，抱歉，另外也要谢谢你这个项目，因为再、我们自己项目好多人忘记切上下文，我给切换加到handleResp里面了，现在看来不用了。不过如果是其他异步 比如处理数据库，在框架层还是加上withContext（IO),不知道room需不需要切换，明天还是瞅瞅，再次为自己的不礼貌行为道歉。
————————————————————————————————————————————
电脑没在身边，应该是这样吧?多谢了

**Comment by ghost** [comment]
> @Temtion 还没明白吗，问题在于1. 你想知道的别人未必想知道，2. 别人知道的未必要告诉你，这个issue到2楼就可以结束了，之后就该你自己去研究retrofit了，
> 
> 就当我咸的，我给你看看吧，
> 
> 结论是，协程确实是运行在主线程，没有用调度器什么的也不需要，retrofit默认是使用okhttp的io线程池异步请求的网络，
> 
> 看你上面已经找到.await()->enque()，那这之前就不说了，然后就是， retrofit/src/main/java/retrofit2/Call.java:49 默认实现在， retrofit/src/main/java/retrofit2/OkHttpCall.java:147
> 
> ```java
>     okhttp3.Call call;
>     call.enqueue(...);
> ```
> 
> 然后就到了okhttp项目里了， https://github.com/square/okhttp okhttp/src/main/java/okhttp3/Call.java:71 默认实现在， okhttp/src/main/java/okhttp3/RealCall.java:93
> 
> ```java
>     client.dispatcher().enqueue(new AsyncCall(responseCallback));
> ```
> 
> okhttp/src/main/java/okhttp3/Dispatcher.java:135
> 
> ```java
>       readyAsyncCalls.add(call);
> ```
> 
> 把call加入列表中然后当前线程就返回了，
> 
> 到这里已经知道这里retrofit没有在主线程进行网络连接了，
> 
> 然后readyAsyncCalls是在promoteAndExecute方法中取出来运行的， okhttp/src/main/java/okhttp3/Dispatcher.java:204
> 
> ```java
>       AsyncCall asyncCall = executableCalls.get(i);
>       asyncCall.executeOn(executorService());
> ```
> 
> 这里的executorService就是okhttp内部用的io线程池了， okhttp/src/main/java/okhttp3/Dispatcher.java:65
> 
> ```java
>       executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE, 60, TimeUnit.SECONDS,
>           new SynchronousQueue<>(), Util.threadFactory("OkHttp Dispatcher", false));
> ```
> 
> 而executeOn就是简单调用execute异步处理的， okhttp/src/main/java/okhttp3/RealCall.java:154
> 
> ```java
>         executorService.execute(this);
> ```
> 
> execute再进去就是java内部了，

多谢了，今天搞一天了，你点醒了我，不介意的话，留个zfb。或者加我qq7656472289
引申下，这个取消外部调度职责，retrofit是出于什么考虑？希望可以探讨下

**Comment by AoEiuV020** [comment]
@Temtion 
> 是不是retrofit 对 非挂起处理是call.execute(),
> 挂起处理是 call.enqueue() ？

是，retrofit中的call也有分成这两个方法，这就已经是“retrofit做了线程切换这方面的操作”
```java
public interface Call<T> extends Cloneable {
  Response<T> execute() throws IOException;
  void enqueue(Callback<T> callback);
}
```

> 如今只是协程 替换掉了rx，会不会奇怪?

rx本来就不是必须的，在我看来rx主要是解决java链式调用 集合处理和切回主线程不方便的问题的，retrofit默认也是不依赖rx的，
切回主线程也不是必须的，以前必须主线程更新ui但现在可以mvvm间接的来，

> 取消外部调度职责，retrofit是出于什么考虑？

一个考虑肯定是为了方便了，少一个需要关注的点，本来考虑线程切换就挺麻烦，

> 不介意的话，留个zfb。或者加我qq7656472289

是要打钱吗，虽然挺心动的但这里收钱就丑陋了，

**Comment by ficapy** [comment]
先学会做个人吧

**Comment by ghost** [comment]
> @Temtion
> 
> > 是不是retrofit 对 非挂起处理是call.execute(),
> > 挂起处理是 call.enqueue() ？
> 
> 是，retrofit中的call也有分成这两个方法，这就已经是“retrofit做了线程切换这方面的操作”
> 
> ```java
> public interface Call<T> extends Cloneable {
>   Response<T> execute() throws IOException;
>   void enqueue(Callback<T> callback);
> }
> ```
> 
> > 如今只是协程 替换掉了rx，会不会奇怪?
> 
> rx本来就不是必须的，在我看来rx主要是解决java链式调用 集合处理和切回主线程不方便的问题的，retrofit默认也是不依赖rx的， 切回主线程也不是必须的，以前必须主线程更新ui但现在可以mvvm间接的来，
> 
> > 取消外部调度职责，retrofit是出于什么考虑？
> 
> 一个考虑肯定是为了方便了，少一个需要关注的点，本来考虑线程切换就挺麻烦，
> 
> > 不介意的话，留个zfb。或者加我qq7656472289
> 
> 是要打钱吗，虽然挺心动的但这里收钱就丑陋了，

你说呢？不能放过你呀，碰到较真的工匠，还是要多谢你的，毕竟正面打脸一次，这次刨地太不容易了我。
这里想交个朋友，算我欠你一次。

**Comment by ldlywt** [comment]
@Temtion 

其实没必要的跟他扯这么多的

看这个人在其他github的评论就知道了这个人的素质什么样

https://github.com/yescpu/KeyboardChangeListener/issues/9

[![5cqn1J.md.png](https://z3.ax1x.com/2021/10/22/5cqn1J.md.png)](https://imgtu.com/i/5cqn1J)

**Comment by LudwigWS** [comment]
不如直接发聊天记录，孰是孰非一目了然

**Comment by gou7ma7** [comment]
看了这个兄弟的回复，太秀了，活像我初中的时候的样子，感觉有礼貌的成年人想学这个口气和视野都学不来。

真的就像我初中的时候一样，自我意识过强，完全不知道如何礼貌的和别人交流；

活像我初中的时候去疯狂喜欢一个妹子，天天给人家买东西嘘寒问暖，还怪人家为什么不理我，人家喜欢帅哥，理我干嘛咧，就像高手也是喜欢同样和高手探讨问题，而不是当一个不收钱的客服一样。

往好了想，说不定当事人是一位搞安卓的初中生呢。

我总结以下：

“因为如果不是你，这个事情压根不会有。”

“也请领袖爱惜自己的羽毛，不要发一些自己不是特别透彻的”

“你点醒了我，不介意的话，留个zfb。或者加我qq **”

“你说呢？不能放过你呀，碰到较真的工匠，还是要多谢你的”

“这里想交个朋友，算我欠你一次。”

**Comment by ldlywt** [comment]
对帖子的补充与终结 [现在在 github 开源项目上不回答别人的问题，都是错了么]

https://v2ex.com/t/809972
