### ISSUE TITLE
试用了大佬的封装，想请教一个有关ApiResponse类的问题

### ISSUE THREAD

**Issue by BraveMomo** [ldlywt/FastJetpack#7]
我这边的数据返回的数据不太规范，或者说后台比较灵活，ApiResponse里data有时候不是data，有时候是多个bean，比如{data1：xx，data2：xx，code：xx，message：xx}，我尝试去修改ApiResponse，但是发现不生效，请问能怎么扩展这个ApiResponse呢，我按照以下的写法，参考message的调用方法调用，无法成功，我在调用函数的时候，泛型使用的是UserInfo，但是实际上data拿不到，后台数据是用userInfo包裹的，所以我就加上一个，当然，如果我重写一套Response应该能实现，但是这样就太多样板代码了，总觉得

open class ApiResponse<T>(
    open val data: T? = null,
    open val userInfo: UserInfo? = null,
    open val code: Int? = null,
    open val message: String? = null,
    open val error: Throwable? = null,
) : Serializable {
    val isSuccess: Boolean
        get() = (code == 1 || code == 200)
}

data class ApiSuccessResponse<T>(val response: T) : ApiResponse<T>(
    data = response
)

data class ApiLoginResponse<T>(override val userInfo: UserInfo?) :
    ApiResponse<T>(userInfo = userInfo)

class ApiEmptyResponse<T> : ApiResponse<T>()

data class ApiFailedResponse<T>(override val code: Int?, override val message: String?) :
    ApiResponse<T>(code = code, message = message)

data class ApiErrorResponse<T>(val throwable: Throwable) :
    ApiResponse<T>(error = throwable)

**Comment by ldlywt** [comment]
后台返回的结果必须要遵循 RESTful API。

如果后台返回的是类试这种：{data:{}}，那就只定一个最基础的bean，其他的按需要扩展，如下：

class ApiResponse<T>(val data: T?)

还有像UserInfo这种跟业务有关的bean，不要封装在最顶层的ApiResponse里面，因为很多接口都不需要返回UserInfo
